server:
  port: 8081

# Database Config
spring:
  datasource:
    url: jdbc:h2:file:./data/irdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true